ci: add test reporting for instrumentated tests
also disable gradle daemon for executions

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -12,6 +12,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+
       - name: set up JDK 11
         uses: actions/setup-java@v3
         with:
@@ -23,13 +24,13 @@ jobs:
         run: chmod +x gradlew
 
       - name: Build with Gradle
-        run: ./gradlew build
+        run: ./gradlew --no-daemon build
 
       - name: Test Report
         uses: dorny/test-reporter@v1
         if: success() || failure()    # run this step even if previous step failed
         with:
-          name: Java Tests            # Name of the check run which will be created
+          name: Unit Tests            # Name of the check run which will be created
           path: "**/test-results/**/*.xml"    # Path to test results
           reporter: java-junit        # Format of test results
 
@@ -52,4 +53,12 @@ jobs:
         with:
           arch: 'x86_64'
           api-level: 30
-          script: ./gradlew connectedCheck
+          script: ./gradlew --no-daemon connectedCheck
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Instrumentation Tests            # Name of the check run which will be created
+          path: "**/androidTest-results/**/*.xml"    # Path to test results
+          reporter: java-junit        # Format of test results
